version: '2.4'
services:
  pihole:
    image: 'pihole/pihole:latest'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    environment:
      TZ: 'America/Boise'
      WEBPASSWORD: 'password'
      DNSMASQ_USER: 'root'
#      ServerIP: '192.168.0.2'
#      FTLCONF_REPLY_ADDR4: '192.168.0.2'
    volumes:
      - 'pihole-volume:/etc'
    networks:
#      lannet:
#        ipv4_address: 192.168.0.2
      - lannet
volumes:
  pihole-volume:
    driver: local
networks:
  lannet:
    driver: bridge
    driver_opts:
      com.cradlepoint.network.bridge.uuid: 00000000-0d93-319d-8220-4a1fb0372b51
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
